name: pages

on:
  push:
    branches: ["main"]

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo "::set-output name=location::$(npm config get cache)"
        name: Configure
        id: npm-cache
        shell: bash

      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.location }}
          key: build-linux-npm-${{ hashFiles('./package-lock.json') }}
          restore-keys: build-linux-npm-

      - run: |
          npm install
          git diff --exit-code
        name: Prepare
        working-directory: ./www/

      - run: npm run build
        name: Build
        working-directory: ./www/

      - uses: actions/upload-pages-artifact@v1.0.4
        name: Upload
        with:
          path: ./www/build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
