name: release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        release:
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   executable: kirbo
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            executable: kirbo
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            executable: kirbo.exe
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            executable: kirbo.exe
          - os: macos-latest
            target: aarch64-apple-darwin
            executable: kirbo
          - os: macos-latest
            target: x86_64-apple-darwin
            executable: kirbo

    name: ${{ matrix.release.target }}
    runs-on: ${{ matrix.release.os }}

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/cache@v3
        name: Configure cache
        with:
          path: |
            ~/.cargo/
            ./build/
          key: release-${{ matrix.release.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: release-${{ matrix.release.target }}-cargo-

      - run: rustup target add ${{ matrix.release.target }}
        name: Prepare — ${{ matrix.release.target }}

      - run: cargo build --target ${{ matrix.release.target }} --release
        name: Build — ${{ matrix.release.target }}

      - run: tar -a -cf kirbo-${{ github.ref }}-${{ matrix.release.target }}.tar.gz ${{ matrix.release.executable }}

      # - uses: actions/upload-artifact@v3
      #   name: Upload — ${{ matrix.release.target }}
      #   with:
      #     name: ${{ matrix.release.target }}-kirbo
      #     path: ./build/${{ matrix.release.target }}/release/${{ matrix.release.executable }}

      - uses: softprops/action-gh-release@v1
        name: Release
        files: ./build/${{ matrix.release.target }}/release/kirbo-${{ github.ref }}-${{ matrix.release.target }}.tar.gz
