name: release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        release:
          # TODO: Figure out how to "setup pkg-config for cross-compilation"
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   executable: kirbo

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            executable: kirbo

          - os: windows-latest
            target: aarch64-pc-windows-msvc
            executable: kirbo.exe

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            executable: kirbo.exe

          - os: macos-latest
            target: aarch64-apple-darwin
            executable: kirbo

          - os: macos-latest
            target: x86_64-apple-darwin
            executable: kirbo

    name: ${{ matrix.release.target }}
    runs-on: ${{ matrix.release.os }}

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/cache@v3
        name: Configure cache
        with:
          path: |
            ~/.cargo/
            ./build/
          key: release-${{ matrix.release.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: release-${{ matrix.release.target }}-cargo-

      - run: rustup target add ${{ matrix.release.target }}
        name: Prepare — ${{ matrix.release.target }}

      - run: cargo build --target ${{ matrix.release.target }} --release
        name: Build — ${{ matrix.release.target }}

      - run: tar -a -cf kirbo-${{ github.ref_name }}-${{ matrix.release.target }}.tar.gz ${{ matrix.release.executable }}
        name: Package (tar) — ${{ matrix.release.target }}
        working-directory: ./build/${{ matrix.release.target }}/release/

      - run: zip -r kirbo-${{ github.ref_name }}-${{ matrix.release.target }}.zip ${{ matrix.release.executable }}
        name: Package (zip) — ${{ matrix.release.target }}
        working-directory: ./build/${{ matrix.release.target }}/release/
        if: ${{ !startsWith(matrix.release.os, 'windows') }}

      - run: Compress-Archive ${{ matrix.release.executable }} -DestinationPath kirbo-${{ github.ref_name }}-${{ matrix.release.target }}.zip
        name: Package (zip) — ${{ matrix.release.target }}
        working-directory: ./build/${{ matrix.release.target }}/release/
        if: ${{ startsWith(matrix.release.os, 'windows') }}

      - uses: softprops/action-gh-release@v1
        name: Publish
        # prerelease: true
        with:
          files: ./build/${{ matrix.release.target }}/release/kirbo-${{ github.ref_name }}-${{ matrix.release.target }}.*

      # We don't want the archives to be stored in the cache of the build directory
      - run: rm kirbo-${{ github.ref_name }}-${{ matrix.release.target }}.*
        name: Cleanup
        working-directory: ./build/${{ matrix.release.target }}/release/
