name: release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    strategy:
      matrix:
        release:
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            executable: kirbo
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            executable: kirbo
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            executable: kirbo.exe
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            executable: kirbo.exe
          - os: macos-latest
            target: aarch64-apple-darwin
            executable: kirbo
          - os: macos-latest
            target: x86_64-apple-darwin
            executable: kirbo

    runs-on: ${{ matrix.release.os }}

    steps:
      - uses: actions/checkout@v3

      - run: echo "::set-output name=target-directory::$(cargo metadata --format-version=1 | jq .target_directory -r)"
        id: config
        shell: bash

      - uses: actions/cache@v3
        name: Meta — Cache (6/12)
        with:
          path: |
            ~/.cargo/
            ${{ steps.config.outputs.target-directory }}
          key: release-${{ matrix.release.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: release-${{ matrix.release.os }}-cargo-

      - run: cargo build --target ${{ matrix.release.target }} --release
        name: Build — ${{ matrix.release.target }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.release.target }}-${{ matrix.executable }}
          path: ${{ steps.config.outputs.target-directory }}/${{ matrix.release.target }}/release/${{ matrix.release.executable }}
