name: release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    strategy:
      matrix:
        - os: ubuntu-latest
          target: aarch64-unknown-linux-gnu
          executable: kirbo
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          executable: kirbo
        - os: windows-latest
          target: aarch64-pc-windows-msvc
          executable: kirbo.exe
        - os: windows-latest
          target: x86_64-pc-windows-msvc
          executable: kirbo.exe
        - os: macos-latest
          target: aarch64-apple-darwin
          executable: kirbo
        - os: macos-latest
          target: x86_64-apple-darwin
          executable: kirbo

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - run: echo "::set-output name=target-directory::$(cargo metadata --format-version=1 | jq .target_directory -r)"
        id: config
        shell: bash

      - uses: actions/cache@v3
        name: Meta — Cache (6/12)
        with:
          path: |
            ~/.cargo/
            ${{ steps.config.outputs.target-directory }}
          key: release-${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: release-${{ matrix.os }}-cargo-

      - run: cargo build --target ${{ matrix.target }} --release
        name: Build — ${{ matrix.target }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-${{ matrix.executable }}
          path: ${{ steps.config.outputs.target-directory }}/${{ matrix.target }}/release/${{ matrix.executable }}
